In [ ]:
# Missing Values in Pandas
# 1. What are Missing Values?

# Missing values are data points that are not available or have not been recorded in a dataset.

# For example, consider a student dataset:

# Name	Age	Marks	City
# Rahul	20	85	Delhi
# Priya	21	NaN	Mumbai
# Amit	NaN	78	Delhi
# Neha	22	90	NaN

# Here, NaN represents a missing value.

# In Pandas, missing data can commonly be represented by:

# NaN — Not a Number
# None — Python's null value
# NaT — Not a Time, used for missing datetime values
# pd.NA — Pandas' newer missing-value indicator

# 2. Why do Missing Values Occur?

# Missing values can occur for several reasons:

# Data was not entered

# Age = NaN
# Data was unavailable
# Data collection errors
# Different datasets were combined, resulting in unmatched records.
# A value does not apply to a particular observation.

# Missing values can cause problems during data analysis and machine learning, so they generally need to be handled appropriately.

In [17]:
#3. Creating a DataFrame with Missing Values
import pandas as pd
import numpy as np

data = {
    'Name': ['Rahul', 'Priya', 'Amit', 'Neha', 'Ravi'],
    'Age': [20, 21, np.nan, 22, 23],
    'Marks': [85, np.nan, 78, 90, np.nan],
    'City': ['Delhi', 'Mumbai', 'Delhi', np.nan, 'Noida']
}

df = pd.DataFrame(data)

print(df)

    Name   Age  Marks    City
0  Rahul  20.0   85.0   Delhi
1  Priya  21.0    NaN  Mumbai
2   Amit   NaN   78.0   Delhi
3   Neha  22.0   90.0     NaN
4   Ravi  23.0    NaN   Noida

In [2]:
# 4. How to Identify Missing Values in Pandas?
# A. isnull()

# The isnull() function checks whether values are missing.
print(df.isnull())

    Name    Age  Marks   City
0  False  False  False  False
1  False  False   True  False
2  False   True  False  False
3  False  False  False   True
4  False  False   True  False

In [3]:
# B. isna()

# isna() does exactly the same thing as isnull().

print(df.isna())

    Name    Age  Marks   City
0  False  False  False  False
1  False  False   True  False
2  False   True  False  False
3  False  False  False   True
4  False  False   True  False

In [4]:
# C. Count Missing Values in Each Column

# A very useful technique is:

print(df.isnull().sum())

Name     0
Age      1
Marks    2
City     1
dtype: int64

In [5]:
#D. Find the Total Number of Missing Values

print(df.isnull().sum().sum())

4

In [6]:
#E. Find Rows Containing Missing Values
print(df[df.isnull().any(axis=1)])

    Name   Age  Marks    City
1  Priya  21.0    NaN  Mumbai
2   Amit   NaN   78.0   Delhi
3   Neha  22.0   90.0     NaN
4   Ravi  23.0    NaN   Noida

In [7]:
#F. Check Whether Any Missing Value Exists
print(df.isnull().any().any())

True

In [8]:
#6. Deleting Missing Values
df_new = df.dropna()

print(df_new)

    Name   Age  Marks   City
0  Rahul  20.0   85.0  Delhi

In [9]:
#B. Delete Rows Only If All Values Are Missing
df.dropna(how='all')

    Name   Age  Marks    City
0  Rahul  20.0   85.0   Delhi
1  Priya  21.0    NaN  Mumbai
2   Amit   NaN   78.0   Delhi
3   Neha  22.0   90.0     NaN
4   Ravi  23.0    NaN   Noida

In [15]:
#C. Delete Columns Containing Missing Values
df.dropna(axis=1)

    Name  Marks
0  Rahul   85.0
1  Priya    0.0
2   Amit   78.0
3   Neha   90.0
4   Ravi    0.0

In [20]:
#7. Imputing Missing Values
df['Marks'] = df['Marks'].fillna(0)
print(df['Marks'])

0    85.0
1     0.0
2    78.0
3    90.0
4     0.0
Name: Marks, dtype: float64

In [28]:
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())
print(df['Marks'])

0    50.6
1    50.6
2    50.6
3    50.6
4    50.6
Name: Marks, dtype: float64