In [1]:
# 1. Import libraries and CSV files
import pandas as pd
import numpy as np

students = pd.read_csv("Student.csv")
marks = pd.read_csv("Mark.csv")

print("Students DataFrame:")
display(students.head())

print("Marks DataFrame:")
display(marks.head())

Students DataFrame:

   Student_id  Age  Gender      Grade Employed
0           1   19    Male  1st Class      yes
1           2   20  Female  2nd Class       no
2           3   18    Male  1st Class       no
3           4   21  Female  2nd Class       no
4           5   19    Male  1st Class       no

Marks DataFrame:

   Student_id  Mark     City
0           1    95  Chennai
1           2    70    Delhi
2           3    98   Mumbai
3           4    75     Pune
4           5    89    Kochi

In [3]:
# 2. Check column names

print("Students columns:")
print(students.columns.tolist())

print("\nMarks columns:")
print(marks.columns.tolist())

Students columns:
['Student_id', 'Age', 'Gender', 'Grade', 'Employed']

Marks columns:
['Student_id', 'Mark', 'City']

In [6]:
# (a) Combine both dataframes
df = pd.merge(students, marks, on="Student_id", how="outer")

print("Combined DataFrame:")
display(df)

Combined DataFrame:

     Student_id  Age  Gender      Grade Employed  Mark     City
0             1   19    Male  1st Class      yes  95.0  Chennai
1             2   20  Female  2nd Class       no  70.0    Delhi
2             3   18    Male  1st Class       no  98.0   Mumbai
3             4   21  Female  2nd Class       no  75.0     Pune
4             5   19    Male  1st Class       no  89.0    Kochi
..          ...  ...     ...        ...      ...   ...      ...
227         228   21  Female  1st Class       no  99.0     Pune
228         229   20    Male  2nd Class       no  70.0  Chennai
229         230   20    Male  3rd Class      yes  55.0    Delhi
230         231   19  Female  1st Class      yes  97.0   Mumbai
231         232   20    Male  3rd Class      yes  59.0     Pune

[232 rows x 7 columns]

In [9]:
#(b) Maximum and minimum marks gender-wise
gender_wise_marks = df.groupby("Gender")["Mark"].agg(
    Maximum_Marks="max",
    Minimum_Marks="min"
)

print(gender_wise_marks)

        Maximum_Marks  Minimum_Marks
Gender
Female           99.0           40.0
Male            100.0           40.0

In [11]:
# (c) Students who scored more than class average
average_marks = df["Mark"].mean()

print("Class Average Marks:", average_marks)

above_average = df[df["Mark"] > average_marks][["Student_id", "Mark"]]

print("\nStudents scoring more than class average:")
display(above_average)

Class Average Marks: 71.38864628820961

Students scoring more than class average:

     Student_id  Mark
0             1  95.0
2             3  98.0
3             4  75.0
4             5  89.0
11           12  90.0
..          ...   ...
221         222  74.0
222         223  79.0
224         225  72.0
227         228  99.0
230         231  97.0

[137 rows x 2 columns]

In [13]:
# (d) Males who are employed
male_employed = df[
    (df["Gender"] == "Male") &
    (df["Employed"] == "yes")
]

display(male_employed)

     Student_id  Age Gender      Grade Employed  Mark     City
0             1   19   Male  1st Class      yes  95.0  Chennai
5             6   20   Male  2nd Class      yes  69.0  Gwalior
7             8   21   Male  3rd Class      yes  54.0  Chennai
12           13   19   Male  1st Class      yes  92.0  Gwalior
14           15   19   Male  1st Class      yes  97.0     Pune
16           17   20   Male  2nd Class      yes  68.0  Gwalior
18           19   21   Male  2nd Class      yes  72.0  Chennai
29           30   19   Male  1st Class      yes  81.0  Chennai
34           35   20   Male  2nd Class      yes  79.0  Gwalior
36           37   21   Male  3rd Class      yes  53.0     Pune
41           42   19   Male  1st Class      yes  86.0    Delhi
43           44   19   Male  1st Class      yes  95.0     Pune
45           46   20   Male  2nd Class      yes  79.0    Delhi
47           48   21   Male  2nd Class      yes  67.0     Pune
58           59   19   Male  1st Class      yes  89.0     Pune
63           64   20   Male  2nd Class      yes  78.0    Delhi
65           66   21   Male  3rd Class      yes  59.0     Pune
70           71   19   Male  1st Class      yes  85.0    Kochi
72           73   19   Male  1st Class      yes  89.0   Bhopal
74           75   20   Male  2nd Class      yes  79.0    Delhi
76           77   21   Male  2nd Class      yes  77.0     Pune
87           88   19   Male  1st Class      yes  96.0     Pune
92           93   20   Male  2nd Class      yes  74.0    Kochi
94           95   21   Male  3rd Class      yes  50.0   Bhopal
99          100   19   Male  1st Class      yes  84.0    Kochi
101         102   19   Male  1st Class      yes  98.0  Chennai
103         104   20   Male  2nd Class      yes  78.0   Mumbai
105         106   21   Male  2nd Class      yes  77.0    Kochi
116         117   19   Male  1st Class      yes  90.0    Kochi
121         122   20   Male  2nd Class      yes  75.0   Mumbai
123         124   21   Male  3rd Class      yes  49.0  Chennai
128         129   19   Male  1st Class      yes  89.0  Gwalior
130         131   19   Male  1st Class      yes  90.0  Chennai
132         133   20   Male  2nd Class      yes  75.0   Mumbai
134         135   21   Male  2nd Class      yes  75.0    Kochi
145         146   19   Male  1st Class      yes  98.0   Mumbai
150         151   20   Male  2nd Class      yes  78.0     Pune
152         153   21   Male  3rd Class      yes  46.0  Gwalior
157         158   19   Male  1st Class      yes  92.0     Pune
159         160   19   Male  1st Class      yes  92.0    Delhi
161         162   20   Male  2nd Class      yes  79.0     Pune
163         164   21   Male  2nd Class      yes  75.0  Gwalior
174         175   19   Male  1st Class      yes  84.0     Pune
179         180   20   Male  2nd Class      yes  76.0    Delhi
181         182   21   Male  3rd Class      yes  58.0     Pune
186         187   19   Male  1st Class      yes  83.0    Kochi
188         189   19   Male  1st Class      yes  89.0   Bhopal
190         191   20   Male  2nd Class      yes  77.0    Delhi
192         193   21   Male  2nd Class      yes  75.0     Pune
203         204   19   Male  1st Class      yes  91.0     Pune
208         209   20   Male  2nd Class      yes  70.0   Mumbai
210         211   21   Male  3rd Class      yes  58.0    Kochi
215         216   19   Male  1st Class      yes  95.0   Mumbai
217         218   19   Male  1st Class      yes  96.0    Kochi
219         220   20   Male  2nd Class      yes  75.0   Bhopal
221         222   21   Male  2nd Class      yes  74.0    Kochi
229         230   20   Male  3rd Class      yes  55.0    Delhi
231         232   20   Male  3rd Class      yes  59.0     Pune

In [15]:
#(e) Create IQ_level

#The condition needs to be interpreted as:

#Marks > 80 → Intelligent
#Marks 50–80 → Mediocre
#Marks < 50 → Weak

def assign_iq_level(marks):
    if marks > 80:
        return "Intelligent"
    elif marks >= 50:
        return "Mediocre"
    else:
        return "Weak"

df["IQ_level"] = df["Mark"].apply(assign_iq_level)

display(df)

     Student_id  Age  Gender      Grade Employed  Mark     City     IQ_level
0             1   19    Male  1st Class      yes  95.0  Chennai  Intelligent
1             2   20  Female  2nd Class       no  70.0    Delhi     Mediocre
2             3   18    Male  1st Class       no  98.0   Mumbai  Intelligent
3             4   21  Female  2nd Class       no  75.0     Pune     Mediocre
4             5   19    Male  1st Class       no  89.0    Kochi  Intelligent
..          ...  ...     ...        ...      ...   ...      ...          ...
227         228   21  Female  1st Class       no  99.0     Pune  Intelligent
228         229   20    Male  2nd Class       no  70.0  Chennai     Mediocre
229         230   20    Male  3rd Class      yes  55.0    Delhi     Mediocre
230         231   19  Female  1st Class      yes  97.0   Mumbai  Intelligent
231         232   20    Male  3rd Class      yes  59.0     Pune     Mediocre

[232 rows x 8 columns]

In [16]:
#(f) Count males and females from each city
city_gender_count = (
    df.groupby(["City", "Gender"])
      .size()
      .reset_index(name="Count")
)

display(city_gender_count)

       City  Gender  Count
0    Bhopal  Female     13
1    Bhopal    Male     15
2   Chennai  Female     15
3   Chennai    Male     18
4     Delhi  Female     12
5     Delhi    Male     20
6   Gwalior  Female     14
7   Gwalior    Male     18
8     Kochi  Female     10
9     Kochi    Male     21
10   Mumbai  Female     16
11   Mumbai    Male     16
12     Pune  Female     15
13     Pune    Male     26

In [17]:
#(g) Top 5 male scorers
top_5_males = (
    df[df["Gender"] == "Male"]
    .sort_values(by="Mark", ascending=False)
    .head(5)
)

display(top_5_males)

     Student_id  Age Gender      Grade Employed   Mark     City     IQ_level
149         150   19   Male  1st Class       no  100.0   Bhopal  Intelligent
147         148   18   Male  1st Class       no   99.0    Kochi  Intelligent
62           63   19   Male  1st Class       no   98.0  Chennai  Intelligent
60           61   18   Male  1st Class       no   98.0  Gwalior  Intelligent
2             3   18   Male  1st Class       no   98.0   Mumbai  Intelligent

In [22]:
# (h) Replace Male/Female with M/F and export
df_export = df.copy()

df_export["Gender"] = df_export["Gender"].replace({
    "Male": "M",
    "Female": "F"
})

display(df_export)

df_export.to_csv(r"C:\Users\pc\Data_Science\Assignment_Python\Panda\test.csv", index=False)

     Student_id  Age Gender      Grade Employed  Mark     City     IQ_level
0             1   19      M  1st Class      yes  95.0  Chennai  Intelligent
1             2   20      F  2nd Class       no  70.0    Delhi     Mediocre
2             3   18      M  1st Class       no  98.0   Mumbai  Intelligent
3             4   21      F  2nd Class       no  75.0     Pune     Mediocre
4             5   19      M  1st Class       no  89.0    Kochi  Intelligent
..          ...  ...    ...        ...      ...   ...      ...          ...
227         228   21      F  1st Class       no  99.0     Pune  Intelligent
228         229   20      M  2nd Class       no  70.0  Chennai     Mediocre
229         230   20      M  3rd Class      yes  55.0    Delhi     Mediocre
230         231   19      F  1st Class      yes  97.0   Mumbai  Intelligent
231         232   20      M  3rd Class      yes  59.0     Pune     Mediocre

[232 rows x 8 columns]

In [28]:
# (i) Check duplicate Student_ID
print("========== (i) Duplicate Student_ID ==========")

duplicate_ids = df.loc[
    df["Student_id"].duplicated(keep=False),
    "Student_id"
].unique()

if len(duplicate_ids) == 0:
    print("No duplicate Student_ID found.")
else:
    print("Duplicate Student_IDs:", duplicate_ids)

========== (i) Duplicate Student_ID ==========
No duplicate Student_ID found.

In [31]:
# (j) Integer/Float variables
numeric_df = df.select_dtypes(include=["int64", "int32", "float64", "float32"])

print("Integer/Float variables:")
display(numeric_df)

Integer/Float variables:

     Student_id  Age  Mark
0             1   19  95.0
1             2   20  70.0
2             3   18  98.0
3             4   21  75.0
4             5   19  89.0
..          ...  ...   ...
227         228   21  99.0
228         229   20  70.0
229         230   20  55.0
230         231   19  97.0
231         232   20  59.0

[232 rows x 3 columns]

In [32]:
# (k) IDs present in Students but not Marks
missing_in_marks = students[
    ~students["Student_id"].isin(marks["Student_id"])
]

print("Students present in Students table but not in Marks table:")
display(missing_in_marks[["Student_id"]])

Students present in Students table but not in Marks table:

    Student_id
8            9
9           10
48          49