In [4]:
import pandas as pd

# Load the Netflix CSV file
df = pd.read_csv("netflix.csv")

# Display the dataframe
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries"
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV"
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ..."
...,...,...,...,...,...,...,...,...,...,...,...
8775,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers"
8776,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies"
8777,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies"
8778,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies"
8779,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals"

In [8]:
# a) Print first 5 and last 5 rows

print("First 5 rows:")
display(df.head())

print("Last 5 rows:")
display(df.tail())

First 5 rows:

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries"
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV"
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ..."

Last 5 rows:

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
8775,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers"
8776,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies"
8777,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies"
8778,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies"
8779,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals"

In [10]:
# b) Check number of rows and columns
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 8780
Number of columns: 11

In [13]:
# c) Print all column names
for col in df.columns:
    print(col)

show_id
type
title
director
cast
country
date_added
release_year
rating
duration
listed_in

In [14]:
# d) Descriptive statistics of all variables
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
show_id,8780,8780,s1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
type,8780,2,Movie,6110,NaN,NaN,NaN,NaN,NaN,NaN,NaN
title,8780,8780,Dick Johnson Is Dead,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
director,6150,4516,Rajiv Chilaka,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cast,7956,7671,David Attenborough,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country,7952,745,United States,2809,NaN,NaN,NaN,NaN,NaN,NaN,NaN
date_added,8770,1765,"January 1, 2020",108,NaN,NaN,NaN,NaN,NaN,NaN,NaN
release_year,8780.0,NaN,NaN,NaN,2014.178474,8.827938,1925.0,2013.0,2017.0,2019.0,2021.0
rating,8776,14,TV-MA,3198,NaN,NaN,NaN,NaN,NaN,NaN,NaN
duration,8780,220,1 Season,1788,NaN,NaN,NaN,NaN,NaN,NaN,NaN
listed_in,8780,514,"Dramas, International Movies",361,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# e) Number of unique values for each column
df.nunique()

show_id         8780
type               2
title           8780
director        4516
cast            7671
country          745
date_added      1765
release_year      74
rating            14
duration         220
listed_in        514
dtype: int64

In [17]:
# f) Percentage of missing values for each column
missing_percentage = (
    df.isnull().sum() / len(df) * 100
).round(2)

print(missing_percentage)

show_id          0.00
type             0.00
title            0.00
director        29.95
cast             9.38
country          9.43
date_added       0.11
release_year     0.00
rating           0.05
duration         0.00
listed_in        0.00
dtype: float64

In [22]:
# g) Delete rows where Director is missing
print("Missing Director values:", df['director'].isnull().sum())

# Then delete those rows:
df = df.dropna(subset=['director'])

# Check the new size:
print("New shape:", df.shape)

Missing Director values: 0
New shape: (6150, 11)

In [23]:
# h) Print records where country contains Germany
germany_records = df[
    df['country'].str.contains('Germany', case=False, na=False)
]

display(germany_records)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies"
129,s130,Movie,An Unfinished Life,Lasse Hallström,"Robert Redford, Jennifer Lopez, Morgan Freeman...","Germany, United States","September 1, 2021",2005,PG-13,108 min,Dramas
142,s143,Movie,Freedom Writers,Richard LaGravenese,"Hilary Swank, Patrick Dempsey, Scott Glenn, Im...","Germany, United States","September 1, 2021",2007,PG-13,124 min,Dramas
172,s173,Movie,School of Rock,Richard Linklater,"Jack Black, Joan Cusack, Mike White, Sarah Sil...","United States, Germany","September 1, 2021",2003,PG-13,110 min,"Comedies, Music & Musicals"
...,...,...,...,...,...,...,...,...,...,...,...
8590,s8618,Movie,Trash,Stephen Daldry,"Wagner Moura, Martin Sheen, Rooney Mara, Selto...","United Kingdom, Brazil, Germany","January 1, 2019",2014,R,114 min,"Dramas, Independent Movies, Thrillers"
8634,s8662,Movie,Unfinished Song,Paul Andrew Williams,"Terence Stamp, Gemma Arterton, Christopher Ecc...","United Kingdom, Germany","July 22, 2019",2012,PG-13,94 min,"Comedies, Dramas, Independent Movies"
8641,s8669,Movie,V for Vendetta,James McTeigue,"Natalie Portman, Hugo Weaving, Stephen Rea, St...","United States, United Kingdom, Germany","October 1, 2018",2005,R,132 min,"Action & Adventure, Dramas, Sci-Fi & Fantasy"
8702,s8730,Movie,Where the Money Is,Marek Kanievska,"Paul Newman, Linda Fiorentino, Dermot Mulroney...","Germany, United States, United Kingdom, Canada","January 15, 2020",2000,PG-13,89 min,"Action & Adventure, Comedies, Dramas"
8718,s8746,Movie,Willy Wonka & the Chocolate Factory,Mel Stuart,"Gene Wilder, Jack Albertson, Peter Ostrum, Roy...","United States, East Germany, West Germany","January 1, 2020",1971,G,100 min,"Children & Family Movies, Classic Movies, Come..."

In [10]:
# i) Split Duration into numeric value and string
df[['Duration_value', 'Duration_unit']] = df['duration'].str.split(' ', n=1, expand=True)

df['Duration_value'] = pd.to_numeric(
    df['Duration_value'],
    errors='coerce'
)

display(df[['duration', 'Duration_value', 'Duration_unit']].head(10))

    duration  Duration_value Duration_unit
0     90 min              90           min
1  2 Seasons               2       Seasons
2   1 Season               1        Season
3   1 Season               1        Season
4  2 Seasons               2       Seasons
5   1 Season               1        Season
6     91 min              91           min
7    125 min             125           min
8  9 Seasons               9       Seasons
9    104 min             104           min

In [18]:
# j) Split Date added into date, month and year
df['date_added'] = pd.to_datetime(
    df['date_added'],
    errors='coerce'
)
df['Date'] = df['date_added'].dt.day.astype('Int64')
df['Month'] = df['date_added'].dt.month_name()
df['Year'] = df['date_added'].dt.year.astype('Int64')

display(
    df[['date_added', 'Date', 'Month', 'Year']].head(10)
)

  date_added  Date      Month  Year
0 2021-09-25    25  September  2021
1 2021-09-24    24  September  2021
2 2021-09-24    24  September  2021
3 2021-09-24    24  September  2021
4 2021-09-24    24  September  2021
5 2021-09-24    24  September  2021
6 2021-09-24    24  September  2021
7 2021-09-24    24  September  2021
8 2021-09-24    24  September  2021
9 2021-09-24    24  September  2021

In [21]:
# k) Number of TV Shows/Movies released in each year
release_count = pd.crosstab(
    df['release_year'],
    df['type']
)

print(release_count)

release_count['Total'] = release_count.sum(axis=1)

display(release_count)

yearly_count = df['release_year'].value_counts().sort_index()

print(yearly_count)

type          Movie  TV Show
release_year
1925              0        1
1942              2        0
1943              3        0
1944              3        0
1945              3        1
...             ...      ...
2017            765      265
2018            764      377
2019            628      396
2020            517      435
2021            277      315

[74 rows x 2 columns]

type          Movie  TV Show  Total
release_year
1925              0        1      1
1942              2        0      2
1943              3        0      3
1944              3        0      3
1945              3        1      4
...             ...      ...    ...
2017            765      265   1030
2018            764      377   1141
2019            628      396   1024
2020            517      435    952
2021            277      315    592

[74 rows x 3 columns]

release_year
1925       1
1942       2
1943       3
1944       3
1945       4
        ...
2017    1030
2018    1141
2019    1024
2020     952
2021     592
Name: count, Length: 74, dtype: int64

In [22]:
# l) Rename title to movie_title
df = df.rename(columns={'title': 'movie_title'})

print(df.columns)

Index(['show_id', 'type', 'movie_title', 'director', 'cast', 'country',
       'date_added', 'release_year', 'rating', 'duration', 'listed_in',
       'Duration_value', 'Duration_unit', 'Date', 'Month', 'Year'],
      dtype='str')

In [25]:
# m) Split listed_in into Genre1, Genre2, Genre3
df[['Genre1', 'Genre2', 'Genre3']] = df['listed_in'].str.split(
    ',',
    n=2,
    expand=True
)

df['Genre1'] = df['Genre1'].str.strip()
df['Genre2'] = df['Genre2'].str.strip()
df['Genre3'] = df['Genre3'].str.strip()

display(
    df[['listed_in', 'Genre1', 'Genre2', 'Genre3']].head(10)
)

,listed_in,Genre1,Genre2,Genre3
0,Documentaries,Documentaries,NaN,NaN
1,"International TV Shows, TV Dramas, TV Mysteries",International TV Shows,TV Dramas,TV Mysteries
2,"Crime TV Shows, International TV Shows, TV Act...",Crime TV Shows,International TV Shows,TV Action & Adventure
3,"Docuseries, Reality TV",Docuseries,Reality TV,NaN
4,"International TV Shows, Romantic TV Shows, TV ...",International TV Shows,Romantic TV Shows,TV Comedies
5,"TV Dramas, TV Horror, TV Mysteries",TV Dramas,TV Horror,TV Mysteries
6,Children & Family Movies,Children & Family Movies,NaN,NaN
7,"Dramas, Independent Movies, International Movies",Dramas,Independent Movies,International Movies
8,"British TV Shows, Reality TV",British TV Shows,Reality TV,NaN
9,"Comedies, Dramas",Comedies,Dramas,NaN